# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- task: GoTool@0
  inputs:
    version: '1.15.0'
  displayName: 'Install Go'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Get deps'
- task: Go@0
  inputs:
    command: 'run'
    arguments: 'chart.go'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Make chart'
- script: |
    git config --global user.email "nick@e3b0c442.io"
    git config --global user.name "Nick Meyer"
    git remote set-url origin https://${GITHUB_PAT}@github.com/e3b0c442/keywords
    git checkout -b new-master
    git add README.md chart.png
    git commit -m "[skip ci] Rebuild README.md and chart.png from chart.yaml update"
    git checkout master
    git merge new-master
    git push origin master
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Push auto-generated content'
  env:
    GITHUB_PAT: $(github_pat)
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'Manual'))



